services:
  - type: web
    name: agritrace-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false          # you fill this in Render dashboard
      - key: JWT_SECRET
        sync: false          # you fill this in Render dashboard
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        sync: false          # your Vercel URL e.g. https://agritrace.vercel.app
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false